### ISSUE TITLE
Invalid set index 'report_token' (on base: 'Node (CodecksUserReport)') with value of type 'String'.

### ISSUE THREAD

**Issue by MichaelGame-Dev** [vnznznz/codecks-user-reports-godot#1]
I have downloaded the test scene and example gd script plus the plugin.

When trying to run the report I get the error above.

This is on the class init:
```gdscript
func _init(report_token_, message_, severity_=SEVERITY_NONE, email_=null):
	self.report_token = report_token_
	self.message = message_
	self.severity = severity_
	self.email = email_
	self.status = self.NEW
```

And looking at the variable assignment, I do see rt_xxxxx (the report id I added) as my report id. So that field is getting filled in.

**Comment by vnznznz** [comment]
Looks like there was an issue with Godot 4.1, can you please try the latest change?
